spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/order
      host: localhost
      port: 27017
      database: order
      repositories:
        enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/